### PR TITLE
Add option to specify a base_path that contains branch subfolders.

### PR DESCRIPTION
**Pull request by mikeNG**

### CODE REVIEW

**Comment by mamantoha** [comment]
Looks good for me :+1:.  But we should test this changes to be assured that everything else is working properly.

**Comment by mikeNG** [comment]
I have made a small test with the new option and seems to work fine. Pushing new CyanogenMod branch at the moment to see if everything is OK.

**Comment by mamantoha** [comment]
Well. I have a question, It's works only for download translations. What about if you want upload sources/translations from specific branch with `base_path_contains_branch_subfolders: true`? You do not need it? Anyway, merge pull request. Thanks.

**Comment by mikeNG** [comment]
Thanks. Source upload works fine as well as translations download. Only thing I haven't tried is translations upload.

**Pull request merged**
